apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  namespace: mario
spec:
  replicas: 2

  selector:
    matchLabels:
      app: mario

  template:
    metadata:
      labels:
        app: mario

    spec:
      containers:
      - name: mario

        image: 172121199482.dkr.ecr.ap-south-1.amazonaws.com/mario:3cf509e626cfb068c1ea7e797f5911601c08f317

        ports:
        - containerPort: 8080
