apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mario-secret
  namespace: mario

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: mario-secret

  data:
    - secretKey: username
      remoteRef:
        key: mario-db-secret
        property: username

    - secretKey: password
      remoteRef:
        key: mario-db-secret
        property: password
