apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/sidharth-sehrawat/AWS-Deployment.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: mario

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
