name: Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

  pull_request:
    paths:
      - 'terraform/**'

jobs:

  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Create tfvars file
        run: |
          cat <<EOF > terraform.tfvars
          ${{ secrets.TF_VARS_FILE }}
          EOF

      - name: Terraform Plan
        env:
          TF_VAR_public_key: ${{ secrets.TF_VAR_public_key }}
        run: terraform plan -var-file=terraform.tfvars -no-color
